import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
Portions derived from obsidian-sidekick, Copyright 2026 Alexandre Vieira, Apache License 2.0
*/
var __import_meta_url__ = typeof __filename !== 'undefined' ? require('url').pathToFileURL(__filename).href : '';
`;

const prod = (process.argv[2] === "production");

// The bundled SDK version is baked in at build time (as opposed to read from
// node_modules at runtime) because only main.js/manifest.json/styles.css are
// deployed to the vault -- node_modules never ships with the plugin. This is
// compared against the resolved CLI's own --version output to surface a
// non-blocking skew warning in Settings -> Claude (see src/runtimeManager.ts).
const sdkPkgPath = fileURLToPath(new URL('./node_modules/@anthropic-ai/claude-agent-sdk/package.json', import.meta.url));
const sdkVersion = JSON.parse(readFileSync(sdkPkgPath, 'utf8')).version;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		// The Claude Agent SDK uses `import.meta.url` in some paths that esbuild
		// encounters when bundling. Since this plugin targets CJS (Obsidian/Electron),
		// `import.meta.url` doesn't exist at runtime. The banner above shims
		// `__import_meta_url__` to `pathToFileURL(__filename).href` so the polyfill
		// works correctly. This define must stay paired with the banner shim.
		'import.meta.url': '__import_meta_url__',
		'__SYNAPSE_SDK_VERSION__': JSON.stringify(sdkVersion),
	},
	entryPoints: ["src/main.ts"],
	// Starter-kit agents/skills (src/starter/) are bundled as text — see src/starterKit.ts.
	loader: {".md": "text"},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map(m => `node:${m}`)],
	format: "cjs",
	platform: "node",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
