import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __import_meta_url__ = typeof __filename !== 'undefined' ? require('url').pathToFileURL(__filename).href : '';
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		// The Claude Agent SDK uses `import.meta.url` in some paths that esbuild
		// encounters when bundling. Since this plugin targets CJS (Obsidian/Electron),
		// `import.meta.url` doesn't exist at runtime. The banner above shims
		// `__import_meta_url__` to `pathToFileURL(__filename).href` so the polyfill
		// works correctly. This define must stay paired with the banner shim.
		'import.meta.url': '__import_meta_url__',
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map(m => `node:${m}`)],
	format: "cjs",
	platform: "node",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
